package cepneuralink;

import sbnz.mrsandman.neuralinkapp.model.events.BrainWaveEvent;
import sbnz.mrsandman.neuralinkapp.model.events.SleepPhaseEvent;
import sbnz.mrsandman.neuralinkapp.model.enums.SleepPhase;

// This file is only left since the test are failing without it (PhysicalActivityCep, SleepStageCep)
// It should be removed since it is replaced by detect-wakeup rule

rule "AWAKE event"
    when
        not(
            BrainWaveEvent() 
            over window:time(10s)
        )
    then
    	System.out.println("Dodat sleep phase event.");
        insert(new SleepPhaseEvent(SleepPhase.AWAKE));
        //drools.halt();
end