package cepneuralink;

import sbnz.mrsandman.neuralinkapp.model.events.alcohol.AlcoholLevelEvent;
import sbnz.mrsandman.neuralinkapp.model.events.alcohol.RaisedAlcoholLevelEvent;

rule "Raised alcohol level event"
	no-loop
    when       
		$al1: AlcoholLevelEvent(permille >= 0.2) 
        Number(intValue >= 3) from accumulate(
        	$al2: AlcoholLevelEvent(
        		this != $al1,
        		permille >= 0.2,
        		this meets[10m] $al1
        	),
        	count($al2) 
        )
        not RaisedAlcoholLevelEvent()
    then
    	System.out.println("Detektovan povisen nivo alkohola u krvi");
        insert(new RaisedAlcoholLevelEvent());
        //drools.halt();
end
