package cepneuralink;

import sbnz.mrsandman.neuralinkapp.model.events.alcohol.*;
import sbnz.mrsandman.neuralinkapp.model.events.heartrate.*;
import sbnz.mrsandman.neuralinkapp.model.events.temperature.*;
import sbnz.mrsandman.neuralinkapp.model.events.physicalactivity.*;
import sbnz.mrsandman.neuralinkapp.model.events.caffeine.*;
import sbnz.mrsandman.neuralinkapp.model.events.light.*;
import sbnz.mrsandman.neuralinkapp.model.events.*;
import sbnz.mrsandman.neuralinkapp.model.enums.*;
import sbnz.mrsandman.neuralinkapp.model.*;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.util.Date;

rule "Raised alcohol level 4 hours before sleep"
	no-loop
    when       
        SleepPhaseEvent(sleepPhase == SleepPhase.AWAKE)
        $u:User(optimalSleepTime != null && optimalSleepTime.compareTo(LocalTime.of(20,0 ,59)) >=0)
		$al1: RaisedAlcoholLevelEvent() 
        Number(intValue >= 3) from accumulate(
        	$al2: RaisedAlcoholLevelEvent(
        		this != $al1,
        		this meets[4h] $al1
        	),
        	count($al2) 
        )
        not(
            AlcoholBeforeSleepEvent() 
            over window:time(4h)
        )
    then
    	System.out.println("Warning! Increased blood alcohol level detected less that 4 hours before optimal sleep time!");
        insert(new AlcoholBeforeSleepEvent(1.0, LocalDateTime.of(12,12,12,20,0,0)));
end


rule "Intense physical activity 2 hours before optimal sleep time"
	no-loop
    when       
        SleepPhaseEvent(sleepPhase == SleepPhase.AWAKE)
        $u:User(optimalSleepTime != null && optimalSleepTime.compareTo(LocalTime.of(20,0 ,59)) >=0)
		$temp: RaisedTemperatureEvent() 
        Number(intValue >= 3) from accumulate(
        	$t: RaisedTemperatureEvent(
        		this != $temp,
        		this meets[10m] $temp
        	),
        	count($t) 
        )
		$hr: HeartRateIncreasedEvent()
        Number(intValue >= 3) from accumulate(
        	$h: HeartRateIncreasedEvent(
        		this != $hr,
        		this meets[10m] $hr
        	),
        	count($h) 
        )
        not(
            PhysicalActivityEvent()
            over window:time(10m)
        )
    then
    	System.out.println("Warning! Intense physical activity 2 hours before optimal sleep time!");
        insert(new PhysicalActivityEvent());
end

rule "Raised caffeine level 6 hours before sleep"
	no-loop
    when       
        SleepPhaseEvent(sleepPhase == SleepPhase.AWAKE)
        $u:User(optimalSleepTime != null && optimalSleepTime.compareTo(LocalTime.of(20,0 ,59)) >=0)
		$cf1: RaisedCaffeineLevelEvent() 
        Number(intValue >= 3) from accumulate(
        	$cf2: RaisedCaffeineLevelEvent(
        		this != $cf1,
        		this meets[10m] $cf1
        	),
        	count($cf2) 
        )
        not(
            CaffeineBeforeSleepEvent() 
            over window:time(10m)
        )
    then
    	System.out.println("Warning! Increased blood caffeine level detected less that 6 hours before optimal sleep time!");
        insert(new CaffeineBeforeSleepEvent());
end

rule "Raised light level 2 hours before sleep"
	no-loop
    when       
        SleepPhaseEvent(sleepPhase == SleepPhase.AWAKE)
        $u:User(optimalSleepTime != null && optimalSleepTime.compareTo(LocalTime.of(20,0 ,59)) >=0)
		$e1: BrightLightEvent() 
        Number(intValue >= 3) from accumulate(
        	$e2: BrightLightEvent(
        		this != $e1,
        		this meets[10m] $e1
        	),
        	count($e2) 
        )
        not(
            BrightLightBeforeSleepEvent() 
            over window:time(10m)
        )
    then
    	System.out.println("Warning! Increased bright light level detected less that 2 hours before optimal sleep time!");
        insert(new BrightLightBeforeSleepEvent());
end
