package cepneuralink;

global sbnz.mrsandman.neuralinkapp.bus.EventBus eventBus;

import sbnz.mrsandman.neuralinkapp.model.*;
import sbnz.mrsandman.neuralinkapp.model.enums.*;
import sbnz.mrsandman.neuralinkapp.model.events.*;
import sbnz.mrsandman.neuralinkapp.model.events.beginsleeping.*;
import sbnz.mrsandman.neuralinkapp.model.events.temperature.*;

rule "Detect wakeup"
	no-loop
	when
		// seems like it is not possible to get the current time in this
		$awakePhase: SleepPhaseEvent(sleepPhase == SleepPhase.AWAKE)
		$s: Sleep(endTime == null)
		$awakeStage: SleepStage(sleep == $s, endTime == null)
	then
		System.out.println("Detektovan wake up event");
		modify ($s) {
			setEndTime(new java.util.Date(drools.getWorkingMemory().getSessionClock().getCurrentTime()));
		};
		insert(new WakeUpEvent());
end