package cepneuralink;

import sbnz.mrsandman.neuralinkapp.model.*;
import sbnz.mrsandman.neuralinkapp.model.enums.*;
import sbnz.mrsandman.neuralinkapp.model.events.*;
import sbnz.mrsandman.neuralinkapp.model.events.movement.*;
import sbnz.mrsandman.neuralinkapp.model.events.somnabulism.*;

rule "Somnabulism detected event"
	no-loop
    when
    	MuscleToneChangedEvent(muscleTone == MuscleTone.TENSE)
    	$s: Sleep()
    	SleepStage(sleepPhase == SleepPhase.REM, endTime == null, sleep == $s)
    	MovementDetectedEvent()
    then
    	System.out.println("Aktivacija detect somnabulism eventa");
        insert(new SomnabulismDetectedEvent());
        // drools.halt();
end




