package cepneuralink;

import sbnz.mrsandman.neuralinkapp.model.*;
import sbnz.mrsandman.neuralinkapp.model.enums.*;
import sbnz.mrsandman.neuralinkapp.model.events.*;
import sbnz.mrsandman.neuralinkapp.model.events.somnabulism.*;

rule "Somnabulism detected event"
    when
    	MuscleToneChangedEvent(muscleTone == MuscleTone.TENSE)
    	$s: Sleep($stages: sleepStages)
    	SleepStage(sleepPhase == SleepPhase.REM, endTime == null) from $stages
    	$u: User(isStatic == false)
    then
    	System.out.println("Aktivacija detect somnabulism eventa");
        insert(new SomnabulismDetectedEvent());
        drools.halt();
end




