package cepneuralink;

global sbnz.mrsandman.neuralinkapp.bus.EventBus eventBus;

import java.time.LocalDate;

import sbnz.mrsandman.neuralinkapp.model.*;
import sbnz.mrsandman.neuralinkapp.model.enums.*;
import sbnz.mrsandman.neuralinkapp.model.events.*;
import sbnz.mrsandman.neuralinkapp.model.events.beginsleeping.*;
import sbnz.mrsandman.neuralinkapp.model.events.temperature.*;
import sbnz.mrsandman.neuralinkapp.model.events.somnabulism.*;

rule "Has insomnia"
	when
		String(this == "Has insomnia")
		isInsomniaDay(LocalDate.now().minusDays(7), output;)
		eval(output >= 3)
	then
		System.out.println("IMA INSOMNIJU");
end

query isInsomniaDay(LocalDate inputDay, Long output)
	output := Number() from accumulate(
		$s: Sleep(day.compareTo(inputDay) >= 0, efficient == false),
		count($s)
	)
end