package cepneuralink;
import sbnz.mrsandman.neuralinkapp.model.*;
import sbnz.mrsandman.neuralinkapp.model.enums.*;
import java.time.LocalTime;

rule "Categorize Chronotype_3 BEAR"
no-loop true
when
    $u: User(goingToBedTime.compareTo(LocalTime.of(22,0 ,59)) >= 0,
			goingToBedTime.compareTo(LocalTime.of(23,59 ,59)) <= 0,
    		isLightSleep == false
    		)
then
	System.out.println("Set chronotype to BEAR");
	modify ($u){ setChronotype(Chronotype.BEAR);}
end

rule "Categorize Chronotype_2 DOLPHIN"
no-loop true
when
    $u: User(goingToBedTime.compareTo(LocalTime.of(0,0 ,59)) >= 0,
			goingToBedTime.compareTo(LocalTime.of(23,59 ,59)) <= 0,
    		isLightSleep == true
    		)
then
	System.out.println("Set chronotype to DOLPHIN");
	modify ($u){ setChronotype(Chronotype.DOLPHIN);}
end

rule "Categorize Chronotype_1 WOLF"
no-loop true
when
    $u: User(goingToBedTime.compareTo(LocalTime.of(0,0 ,59)) >= 0,
			goingToBedTime.compareTo(LocalTime.of(7,0 ,59)) <= 0,
    		isLightSleep == false
    		)
then
	System.out.println("Set chronotype to WOLF");
	modify ($u){ setChronotype(Chronotype.WOLF);}
end

rule "Categorize Chronotype_0 LION"
no-loop true
when
    $u: User(goingToBedTime.compareTo(LocalTime.of(7,0 ,59)) >= 0,
			goingToBedTime.compareTo(LocalTime.of(22,0 ,59)) <= 0,
    		isLightSleep == false
    		)
then
	System.out.println("Set chronotype to LION");
	modify ($u){ setChronotype(Chronotype.LION);}
end


