package chapter07.ruletemplate.simple;
import sbnz.mrsandman.neuralinkapp.model.Sleep;
import sbnz.mrsandman.neuralinkapp.model.enums.SleepPhase;

rule "Categorize Sleep_5"
no-loop true
when
    $c: Sleep(brainwaveFrequency >= 65, 
    			brainwaveFrequency <= 90 
    		)
then
    modify ($c){ setSleepPhase(SleepPhase.REM)};
end

rule "Categorize Sleep_4"
no-loop true
when
    $c: Sleep(brainwaveFrequency >= 50, 
    			brainwaveFrequency <= 65 
    		)
then
    modify ($c){ setSleepPhase(SleepPhase.PHASE4)};
end

rule "Categorize Sleep_3"
no-loop true
when
    $c: Sleep(brainwaveFrequency >= 37.5, 
    			brainwaveFrequency <= 50 
    		)
then
    modify ($c){ setSleepPhase(SleepPhase.PHASE3)};
end

rule "Categorize Sleep_2"
no-loop true
when
    $c: Sleep(brainwaveFrequency >= 25, 
    			brainwaveFrequency <= 37.5 
    		)
then
    modify ($c){ setSleepPhase(SleepPhase.PHASE2)};
end

rule "Categorize Sleep_1"
no-loop true
when
    $c: Sleep(brainwaveFrequency >= 15, 
    			brainwaveFrequency <= 25 
    		)
then
    modify ($c){ setSleepPhase(SleepPhase.PHASE1)};
end

rule "Categorize Sleep_0"
no-loop true
when
    $c: Sleep(brainwaveFrequency >= 0, 
    			brainwaveFrequency <= 15 
    		)
then
    modify ($c){ setSleepPhase(SleepPhase.AWAKE)};
end


