package cepneuralink;
import sbnz.mrsandman.neuralinkapp.model.*;
import sbnz.mrsandman.neuralinkapp.model.enums.SleepPhase;
import sbnz.mrsandman.neuralinkapp.model.events.*;

rule "Categorize Sleep_5"
no-loop true
when
	$s: Sleep()
	Number(intValue >= 100) from accumulate (
		$b: BrainWaveEvent(frequency >= 65, frequency <= 90),
		count($b)
	)
then
    insert(new SleepPhaseEvent(SleepPhase.REM));
    modify($s) {
    	addSleepStage(new SleepStage(SleepPhase.REM));
    }
    
end

rule "Categorize Sleep_4"
no-loop true
when
	$s: Sleep()
	Number(intValue >= 100) from accumulate (
		$b: BrainWaveEvent(frequency >= 50, frequency <= 65),
		count($b)
	)
then
    insert(new SleepPhaseEvent(SleepPhase.PHASE4));
    modify($s) {
    	addSleepStage(new SleepStage(SleepPhase.PHASE4));
    }
    
end

rule "Categorize Sleep_3"
no-loop true
when
	$s: Sleep()
	Number(intValue >= 100) from accumulate (
		$b: BrainWaveEvent(frequency >= 37.5, frequency <= 50),
		count($b)
	)
then
    insert(new SleepPhaseEvent(SleepPhase.PHASE3));
    modify($s) {
    	addSleepStage(new SleepStage(SleepPhase.PHASE3));
    }
    
end

rule "Categorize Sleep_2"
no-loop true
when
	$s: Sleep()
	Number(intValue >= 100) from accumulate (
		$b: BrainWaveEvent(frequency >= 25, frequency <= 37.5),
		count($b)
	)
then
    insert(new SleepPhaseEvent(SleepPhase.PHASE2));
    modify($s) {
    	addSleepStage(new SleepStage(SleepPhase.PHASE2));
    }
    
end

rule "Categorize Sleep_1"
no-loop true
when
	$s: Sleep()
	Number(intValue >= 100) from accumulate (
		$b: BrainWaveEvent(frequency >= 15, frequency <= 25),
		count($b)
	)
then
    insert(new SleepPhaseEvent(SleepPhase.PHASE1));
    modify($s) {
    	addSleepStage(new SleepStage(SleepPhase.PHASE1));
    }
    
end

rule "Categorize Sleep_0"
no-loop true
when
	$s: Sleep()
	Number(intValue >= 100) from accumulate (
		$b: BrainWaveEvent(frequency >= 0, frequency <= 15),
		count($b)
	)
then
    insert(new SleepPhaseEvent(SleepPhase.AWAKE));
    modify($s) {
    	addSleepStage(new SleepStage(SleepPhase.AWAKE));
    }
    
end


