package cepneuralink;
import sbnz.mrsandman.neuralinkapp.model.enums.SignalType;
import sbnz.mrsandman.neuralinkapp.model.events.*;
import sbnz.mrsandman.neuralinkapp.model.events.alcohol.*;
import sbnz.mrsandman.neuralinkapp.model.events.heartrate.*;
import sbnz.mrsandman.neuralinkapp.model.events.caffeine.*;
import sbnz.mrsandman.neuralinkapp.model.events.temperature.*;
import sbnz.mrsandman.neuralinkapp.model.events.light.*;

rule "Categorize Signal_4 - LIGHT_LEVEL between 1000 and 100 and insert new BrightLightEvent"
	no-loop true
	when
		s1: SignalEvent(signalType == SignalType.LIGHT_LEVEL, value >= 1000, value < 100)
	    Number(intValue >= 3) from accumulate(
	    	s2: SignalEvent(
	    		this != s1,
	    		signalType == SignalType.LIGHT_LEVEL,
	    		value >= 1000,
	    		value < 100,
	    		this meets[10s] s1
	    	),
	    	count(s2) 
	    )
        not(
            BrightLightEvent() 
            over window:time(10s)
        )
	then
		insert(new BrightLightEvent());
	end

rule "Categorize Signal_5 - TEMPERATURE between 0 and 36 and insert new LoweredTemperatureEvent"
	no-loop true
	when
		s1: SignalEvent(signalType == SignalType.TEMPERATURE, value >= 0, value < 36)
	    Number(intValue >= 3) from accumulate(
	    	s2: SignalEvent(
	    		this != s1,
	    		signalType == SignalType.TEMPERATURE,
	    		value >= 0,
	    		value < 36,
	    		this meets[10s] s1
	    	),
	    	count(s2) 
	    )
        not(
            LoweredTemperatureEvent() 
            over window:time(10s)
        )
	then
		insert(new LoweredTemperatureEvent());
	end

rule "Categorize Signal_4 - TEMPERATURE between 38 and 100 and insert new RaisedTemperatureEvent"
	no-loop true
	when
		s1: SignalEvent(signalType == SignalType.TEMPERATURE, value >= 38, value < 100)
	    Number(intValue >= 3) from accumulate(
	    	s2: SignalEvent(
	    		this != s1,
	    		signalType == SignalType.TEMPERATURE,
	    		value >= 38,
	    		value < 100,
	    		this meets[10s] s1
	    	),
	    	count(s2) 
	    )
        not(
            RaisedTemperatureEvent() 
            over window:time(10s)
        )
	then
		insert(new RaisedTemperatureEvent());
	end

rule "Categorize Signal_3 - CAFFEINE_LEVEL between 20 and 100 and insert new RaisedCaffeineLevelEvent"
	no-loop true
	when
		s1: SignalEvent(signalType == SignalType.CAFFEINE_LEVEL, value >= 20, value < 100)
	    Number(intValue >= 3) from accumulate(
	    	s2: SignalEvent(
	    		this != s1,
	    		signalType == SignalType.CAFFEINE_LEVEL,
	    		value >= 20,
	    		value < 100,
	    		this meets[10s] s1
	    	),
	    	count(s2) 
	    )
        not(
            RaisedCaffeineLevelEvent() 
            over window:time(10s)
        )
	then
		insert(new RaisedCaffeineLevelEvent());
	end

rule "Categorize Signal_2 - HEART_BEAT between 0 and 100 and insert new HeartRateLoweredEvent"
	no-loop true
	when
		s1: SignalEvent(signalType == SignalType.HEART_BEAT, value >= 0, value < 100)
	    Number(intValue <= 65) from accumulate(
	    	s2: SignalEvent(
	    		this != s1,
	    		signalType == SignalType.HEART_BEAT,
	    		value >= 0,
	    		value < 100,
	    		this meets[60s] s1
	    	),
	    	count(s2) 
	    )
        not(
            HeartRateLoweredEvent() 
            over window:time(60s)
        )
	then
		insert(new HeartRateLoweredEvent());
	end

rule "Categorize Signal_1 - HEART_BEAT between 0 and 100 and insert new HeartRateIncreasedEvent"
	no-loop true
	when
		s1: SignalEvent(signalType == SignalType.HEART_BEAT, value >= 0, value < 100)
	    Number(intValue >= 100) from accumulate(
	    	s2: SignalEvent(
	    		this != s1,
	    		signalType == SignalType.HEART_BEAT,
	    		value >= 0,
	    		value < 100,
	    		this meets[60s] s1
	    	),
	    	count(s2) 
	    )
        not(
            HeartRateIncreasedEvent() 
            over window:time(60s)
        )
	then
		insert(new HeartRateIncreasedEvent());
	end

rule "Categorize Signal_0 - ALCOHOL_LEVEL between 0.2 and 100.0 and insert new RaisedAlcoholLevelEvent"
	no-loop true
	when
		s1: SignalEvent(signalType == SignalType.ALCOHOL_LEVEL, value >= 0.2, value < 100.0)
	    Number(intValue >= 3) from accumulate(
	    	s2: SignalEvent(
	    		this != s1,
	    		signalType == SignalType.ALCOHOL_LEVEL,
	    		value >= 0.2,
	    		value < 100.0,
	    		this meets[10s] s1
	    	),
	    	count(s2) 
	    )
        not(
            RaisedAlcoholLevelEvent() 
            over window:time(10s)
        )
	then
		insert(new RaisedAlcoholLevelEvent());
	end


